### ISSUE TITLE
Match Windows Behavior Exactly?

### ISSUE THREAD

**Issue by zaptrem** [linearmouse/linearmouse#122]
Hello, I have an old Razer mouse that I've been using with Windows to play games for ~10 years. However, no matter how I adjust things (even using the Razer software to set it to 1000 DPI, same as Windows) it still feels completely wrong. The closest I can get it is setting acceleration to zero and DPI to ~2300. 

Is there a guide to get pixel-perfect matching between Windows and MacOS for pointer and direct input (e.g., CSGO/other FPSes)? Thanks!

**Comment by lujjjh** [comment]
You may take a look at #121.

If you disable "Enhance pointer precision" (mouse acceleration) on Windows, you should be able to find a sensitivity in LinearMouse (or DPI in your Razer software) that results in pixel-perfect matching between the two operating systems. However, if "Enhance pointer precision" is enabled, pixel-perfect matching is difficult to achieve because the acceleration curves on Windows and macOS appear to be different.

**Comment by msenol86** [comment]
![0815e052-54b8-49f0-8a25-46d857f5dfe5](https://user-images.githubusercontent.com/2547551/169763345-92552615-45c3-48b8-8f14-2c7b785a6fa8.jpeg)
("Enhance pointer precision" is disabled and Mouse speed is at the middle between slow and fast)

How can I replicate this settings in MacOS via linearmouse? There are acceleration and sensitivity options but no speed option.

**Comment by lujjjh** [comment]
> There are acceleration and sensitivity options but no speed option.

The speed in Windows corresponds to the sensitivity in LinearMouse.

> I set acceleration to 0 and sensitivity to 0.5, so am I correctly replicating the settings in Windows?

No, the pointer speed range in Windows and LinearMouse can differ. So the middle speed can be different as well. If you really want to replicate the settings in Windows *precisely*, you'll have to manually find the sensitivity as I commented [here](https://github.com/linearmouse/linearmouse/discussions/121#discussioncomment-2711449). Otherwise, keep the acceleration at 0 and tweak the sensitivity until you have a comfortable pointer speed.
