### ISSUE TITLE
About mouse "Sensitivity"

### ISSUE THREAD

**Issue by Trepleu** [linearmouse/linearmouse#127]
Hello,

I have successfully checked "_Disable cursor acceleration & sensitivity_".

Using two monitors of 1080p and 4K (both 27"), I'm constantly doubling or halving my DPI (with Logitech app) to keep the same speed in real life.

I would like to add back just a bit of **Acceleration** only (let's say 0.3), however now **Sensitivity** is altering my mouse speed (even when **Acceleration** is set to 0).

So what does **Sensitivity** mean ?
It looks like a DPI multiplier but why doesn't it act linear ?
Is there a neutral value or a way to disable it while keeping a bit of **Acceleration** ?

Thank you for helping me :)

**Comment by lujjjh** [comment]
Thank you for your feedback!

In [v0.6.0-beta.6](https://github.com/linearmouse/linearmouse/releases/tag/v0.6.0-beta.6), I normalized cursor sensitivity and made it linear. Would you like to check if LinearMouse now works as you expected? You may upgrade LinearMouse to that version by checking "Include beta" in the Preferences.

**Comment by Trepleu** [comment]
Nice ! Well actually now I'm used to 0 acceleration and not sure anymore if I want some back, getting rid of my addiction thanks to you :)

**Comment by lujjjh** [comment]
Since v0.6.0 has been out for a few weeks and no one has reported any issues, I'll close this issue.

Feel free to reopen this issue if you have further questions. :)

**Comment by Eagl61** [comment]
In MacOS, in order to completely disable mouse acceleration you should set mouse sensitivity to 0 in MacOS Settings. Then you just can play with DPI of your mouse to get more comfortable mouse sensitivity. No additional software required for this (except, possible, mouse specific).
I've used LiearMouse for turning off mouse acceleration, then I got to know that it can be disable in MacOS itself.
