### ISSUE TITLE
Universal back and forth not working in Firefox

### ISSUE THREAD

**Issue by franco-ruggeri** [linearmouse/linearmouse#246]
Hi,
the universal back and forth feature does not work with:
- MacOS Monterey 12.5.1
- Firefox 91.13.0
- Dell mouse MS5320W or Razer Mamba

Whereas it works properly in the Finder. Anyone else having this problem? Any idea how to fix it?

**Comment by franco-ruggeri** [comment]
I'm not sure how it is implemented, but if it maps the buttons to keyboard shortcuts, I know that by mapping to command+[ (back) and command+] (forth) it works in Firefox, Chrome, and Finder (I made it with Karabiner-Elements, but if it worked LinearMouse I would prefer that).

**Comment by lujjjh** [comment]
Under the hood, LinearMouse converts side button clicks to swipe gestures.

Not in all applications, swipe gestures are equivalent to back and forward (#57, https://github.com/linearmouse/linearmouse/issues/111#issuecomment-1103976810), so the convertions are only enabled in specific apps. Firefox was not on the list since I tested the latest version and the side buttons work.

It seems that in early versions of Firefox, side buttons are not handled correctly. I've now added Firefox into the list and this issue should be fixed in the next release.
