### ISSUE TITLE
all app settings stop working when i use another application

### ISSUE THREAD

**Issue by F4intz** [linearmouse/linearmouse#393]
### OS

macOS 13.0 (Build 22A380)

### LinearMouse

v0.8.0

### Describe the bug

whenever I open another app other than linear mouse the settings that I've applied stop working and only work when I open the linear mouse application.

**Comment by lujjjh** [comment]
LinearMouse supports per-app configuration. It appears that you may have configured the settings for LinearMouse instead of applying them to all apps.

<img width="451" alt="Screenshot 2023-03-23 at 13 50 53" src="https://user-images.githubusercontent.com/3000535/227115606-b20699e3-2fda-4710-ada7-9f179ef683e1.png">
