### ISSUE TITLE
Scroll direction

### ISSUE THREAD

**Issue by minhntp** [linearmouse/linearmouse#395]
### OS

macOS 13.2.1 (Build 22D68)

### LinearMouse

v0.8.0

### Describe the bug

Scroll direction would randomly be inverted.
Host: M1 Macbook
Mouse: Logitech M590
Connection: Unifying receiver

**Comment by lujjjh** [comment]
Thanks for your feedback.

Could you share the logs (#117) when this issue occurs?

**Comment by stimw** [comment]
same

> Thanks for your feedback.
> 
> Could you share the logs (#117) when this issue occurs?

[LinearMouse.log](https://github.com/linearmouse/linearmouse/files/11469977/LinearMouse.log)

**Comment by lujjjh** [comment]
@stimw, thank you for sharing the logs.

I analyzed the raw scrolling events received by LinearMouse. Below is a table containing a portion of the extracted data, including the time and distance of the scroll movement.

Some of the data points have a different scrolling direction compared to the others, but due to the lack of additional information, I cannot confirm whether this is the issue you encountered or if you happened to scroll the mouse wheel in the opposite direction at those particular time points. If you can continuously scroll in one direction and submit the log for that period of time, then we can verify this.

| Time     | Delta Pt |
|----------|---------:|
| 15:10:14 |        1 |
| 15:10:14 |      -10 |
| 15:10:14 |      -13 |
| 15:10:14 |        1 |
| 15:10:14 |        9 |
| 15:10:14 |       -1 |
| 15:10:14 |       -9 |
| 15:10:14 |      -39 |
| 15:10:14 |      -57 |
| 15:10:14 |      -66 |
| 15:10:14 |      -71 |

Since no other issues were found in the log, it is possible that the problem is caused by the mouse itself or other applications. Please verify if this issue can be reproduced after LinearMouse exits. It is worth noting that linear scrolling may amplify this problem, so you might need to observe more carefully.

**Comment by stimw** [comment]
This problem still exists after quitting LinearMouse.

After exiting LinearMouse, my mouse returned to non-linear mode, and the problem became minor. It is especially serious in linear mode.
I had the same problem when using [scroll reverser](https://pilotmoon.com/scrollreverser/), so I switched to LinearMouse. As far as I can remember, it may have appeared after a system version was updated.
I'm not sure if it's a mouse or a system problem.

## OS
macOS 13.3.1 (a) 

## LinearMouse
v0.9.0

## Mouse
Logitech G Pro Wireless Gaming Mouse

**Comment by lujjjh** [comment]
In this case, perhaps you could try testing the mouse on a Windows PC, if available. :)
