### ISSUE TITLE
LinearMouse doesn't detect Counter-Strike Global Offensive

### ISSUE THREAD

**Issue by Yves000** [linearmouse/linearmouse#439]
### OS

macOS 13.3 (Build 22E252)

### LinearMouse

v0.9.0-beta.3

### Describe the bug

I want to configure LinearMouse to disable mouse acceleration for Counter-Strike Global Offensive only, but the dropdown menu does not recognize Counter-Strike Global Offensive whether it is active or not.

### To reproduce

1. Install Counter-Strike Global Offensive from Steam
2. Try to find Counter-Strike Global Offensive in the "Configure for" dropdown menu.

### Expected behavior

I want LinearMouse to be able to detect Counter-Strike Global Offensive in the "Configure for" dropdown menu, so I can only disable mouse acceleration for this app.

**Comment by lujjjh** [comment]
Like the scenario described in #254, CS:GO is not packaged as a macOS app bundle and therefore lacks an app bundle identifier.

An option to consider is using `groupApp` to specify the app bundle ID of the process group for CS:GO, which is likely to be `com.valvesoftware.steam`. An example of this can be found in the [app matching](https://github.com/linearmouse/linearmouse/blob/main/Documentation/Configuration.md#app-matching) section. However, it's worth noting that this would impact all subprocesses generated by Steam. Additionally, a bug in `groupApp` matching has been discovered, which is expected to be addressed in issue #440.

Another option is to add the capability to match a process by its process name instead of its bundle identifier, which should be feasible to implement.
