### ISSUE TITLE
Back and forward button mappings don't work

### ISSUE THREAD

**Issue by bbsixzz** [linearmouse/linearmouse#449]
### OS

macOS 13.3.1 (22E261)

### LinearMouse

 0.9.0-beta.4

### Describe the bug

![Screenshot 2023-04-24 at 22 49 39](https://user-images.githubusercontent.com/47334163/234113964-6582bbbe-2e84-4fe6-b0bf-85740c16e867.png)

When set like this back/forward doesn't work (tested Safari/Finder).

It only works with universal back and forward.

Ideally mapping manually would produce this which has the widest standard compatibility:

<kbd>⌘</kbd> + <kbd>[</kbd> Back
<kbd>⌘</kbd> + <kbd>]</kbd> Forward

(Maybe a future feature request would be to set our own key combinations.)

Apps like https://github.com/dweymouth/supersonic/issues/94 based on https://github.com/fyne-io/fyne that have the correct implementation but not swipe gestures won't work with Linearmouse because of this.

**Comment by lujjjh** [comment]
Due to the fact that fewer apps handle swipe gestures compared to side button clicks (the latter is easier to implement), there is an allowlist in universal back and forward. This means that only the apps on the allowlist will be affected by the feature.

https://github.com/linearmouse/linearmouse/blob/97b45125d456db0c4e7b44928e3cf5d4242d0d15/LinearMouse/EventTransformer/UniversalBackForwardTransformer.swift#L11-L15

Related issues: #57, #246, #274.

Other apps like [supersonic](https://github.com/dweymouth/supersonic), they receive raw button clicks rather than swipe gestures. So you might want to suggest that they handle side button clicks (button #3 and button #4) rather than swipe gestures.
