### ISSUE TITLE
Request for Legacy Support of linearmouse App for macOS Mojave 10.14.6

### ISSUE THREAD

**Issue by stackoverflow1024** [linearmouse/linearmouse#517]
### OS

macOS Mojave 10.14.6

### Is your feature request related to a problem?

Hello,

Linearmouse is a great macOS utility for improving external mouse performance and functionalities. I am reaching out today to discuss a matter concerning compatibility with legacy macOS versions from Intel platforms. Specifically, a lot of users are still using macOS Mojave (10.14) from intel platforms and I've been encountering some difficulties running the latest versions of the linearmouse app. I understand the complexities of maintaining support for legacy operating systems in parallel with developing new features and maintaining up-to-date system compatibility. However, given that Mojave 10.14 still has a significant user base, it would be greatly beneficial if linearmouse could extend its support to include this version.

I believe this legacy support would not only assist myself, but also other users who may not have the option to upgrade their OS due to hardware limitations or other constraints. There may also be users who prefer the Mojave OS for its unique features and stability.

It would be fantastic if your team could consider this request and perhaps provide an update or patch that ensures linearmouse runs smoothly on macOS Mojave 10.14. I truly appreciate your consideration of this issue, and I believe it would make a great difference to users like myself.

Thank you for your time and consideration.

### Describe the solution you'd like

Add support for macOS Mojave 10.14.6

**Comment by lujjjh** [comment]
Currently, the biggest obstacle to supporting earlier versions of macOS is that the user interface technology (specifically, SwiftUI) used by LinearMouse only supports macOS Catalina and newer versions. This means that achieving this goal would require replacing the user interface technology and rewriting the entire user interface, which would be a significant undertaking.

However, I have noticed some performance and compatibility issues with SwiftUI, and since it is closed-source, these issues are not easy to address. Hence, it is possible that I might switch to a different user interface technology in the upcoming major release, which could potentially offer support for Mojave.

**Comment by stackoverflow1024** [comment]
Thanks @lujjjh for the follow up.

I agree, user interface might be a big challenge, if we can separate out it with logic foundations, this might not only apply to legacy macOS, might also be possible to ported to other OS as well.
