### ISSUE TITLE
Make Icon look like macos big sur system icon (3d for example App Store)

### ISSUE THREAD

**Issue by Jomyy** [linearmouse/linearmouse#53]
![LinearMouseICon](https://user-images.githubusercontent.com/62953110/149337377-812b1b71-c007-43a4-9688-d33de9743482.png)

**Comment by lujjjh** [comment]
Thank you for the cool design! I was also thinking about redesigning the icon, but there're things with higher priority. Is this rendered by some 3D modeling software?

**Comment by Jomyy** [comment]
yep i made it in blender in about 10 minutes
i can make a more final one

**Comment by lujjjh** [comment]
> yep i made it in blender in about 10 minutes i can make a more final one

Thank you very much! It would be fantastic, if it won't take up too much of your time.

I wonder if it would be better to make the background and foreground more contrasted (maybe more light on the mouse?), like Mail.app:

<img src="https://user-images.githubusercontent.com/3000535/149457394-7b2e8b87-bda8-46a9-af3c-0783640bab64.png" width="437" />

Also, it would be great if the background is not cropped to a rounded rectangle since macOS icons are actually superellipses, so that I could do some post-processing with the [official templates](https://developer.apple.com/design/resources/#macos-apps).

**Comment by Jomyy** [comment]
Yes i think it could get some more shadows i will try to make another one a bit more final

**Comment by Jomyy** [comment]
here it comes!
![LinearMouse](https://user-images.githubusercontent.com/62953110/149672124-a389a489-5219-4c6c-9a90-e01109ce689d.png)

**Comment by lujjjh** [comment]
Thank you for your efforts! A preview version is available [here](https://github.com/linearmouse/linearmouse/actions/runs/1706370265).

Would you mind open-sourcing this design so that I could improve some details in the future? For example, I have to make it more recongnizable in low resolutions. Also, I need to unify the icons in the menubar and website.

**Comment by Jomyy** [comment]
Yes where should i upload the files?

**Comment by lujjjh** [comment]
> Yes where should i upload the files?

What about [Git LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage)? We could just fork your repository and do some modifications. Of course, uploading them on Google Drive or directly in this issue will also be fine. :)

**Comment by Jomyy** [comment]
https://drive.google.com/file/d/1iZ70viqTwCxVnu8KrzGOkOQFwJJyAMtn/view?usp=sharing

**Comment by Jomyy** [comment]
and yeah it could probably use some more light ontop of the mouse

**Comment by lujjjh** [comment]
> and yeah it could probably use some more light ontop of the mouse

I'll try it when I've learned how to use Blender. 💡

**Comment by Jomyy** [comment]
There is a light directly above it so it should just be selecting it and turning the wattage up in the light settings

**Comment by Jomyy** [comment]
![LinearMouse](https://user-images.githubusercontent.com/62953110/149726313-a28a2cfb-39f6-4ef5-ac8f-57f0bce8e72b.png)
maybe like this?

**Comment by Jomyy** [comment]
![LinearMouse](https://user-images.githubusercontent.com/62953110/149726792-ef4ccfa0-0de5-4466-a38a-e15154e2ff9a.png)
i did some more adjusting in gimp

**Comment by lujjjh** [comment]
Cool! I was playing with the lights. It's not an easy work to me.

![image](https://user-images.githubusercontent.com/3000535/149800262-ab641f8f-975e-4704-8940-5f821b9677ad.png)

The two shadows are a bit strange. But that's okay, they're barely noticeable.

You may try the new build [here](https://github.com/linearmouse/linearmouse/actions/runs/1708753708). Thank you very much!
