### ISSUE TITLE
scrolling modifier keys not working in excel or MS word 

### ISSUE THREAD

**Issue by garfeel** [linearmouse/linearmouse#586]
### MacOS

13.2.1 (22D68)

### LinearMouse

v0.9.3

### Describe the bug

![Greenshot 2023-08-28 16 50 49](https://github.com/linearmouse/linearmouse/assets/48237554/ee219a1c-0040-4692-864d-590b1eca8353)

when i have the "command" key set to "zoom", i am able to command + scroll wheel up/down to zoom in and out on all applications excel microsoft excel and word. onenote, PPT, outlook, etc all appear to work normally 

### To reproduce

1. change command to "zoom" in the modifier keys setting
2. try to command +/- mouse wheel zoom in/out and it will not work in microsoft excel/word 

### Expected behavior

page will zoom in and out per the direction pushed on the scroll wheel

**Comment by lujjjh** [comment]
The "zoom" action in LinearMouse simulates <kbd>⌘</kbd><kbd>numpad+</kbd> and <kbd>⌘</kbd><kbd>numpad-</kbd>, which are compatible with most applications. It appears that MS Word only [recently](https://insider.microsoft365.com/en-us/blog/new-zoom-shortcuts-in-word) added default shortcuts for zooming in and out.

A workaround is to assign the keyboard shortcut for the “ViewZoomIn” and “ViewZoomOut” commands in MS Word. For example, to assign <kbd>⌘</kbd><kbd>numpad+</kbd> to the “ViewZoomIn” command:
1. Click menu Tools -> Customize Keyboard…
2. Select the “ViewZoomIn” command in the “View” category.
3. Focus the keyboard shortcut input and press command + scroll wheel up / down (since it simulates <kbd>⌘</kbd><kbd>numpad+</kbd>.
4. Click “Assign”.

<img width="587" alt="image" src="https://github.com/linearmouse/linearmouse/assets/3000535/77c59c6e-4596-4f48-aec4-3be1b3600da1">

When it comes to MS Excel, the relavent commands are “ZoomIn” and “ZoomOut” in “Commands Not in the Ribbon” category:

<img width="656" alt="image" src="https://github.com/linearmouse/linearmouse/assets/3000535/2a615bb6-7f6a-44fe-8138-4e5ade3f0869">

**Comment by garfeel** [comment]
thank you so much, this is a game changer!!

**Comment by RobaloAmigo** [comment]
How to set in in Sonoma? I don't see any "Customize keyboard..." option
