### ISSUE TITLE
External mouse wakes up my mac few seconds after i put it to sleep

### ISSUE THREAD

**Issue by notAPanda** [linearmouse/linearmouse#605]
### OS

macOS 13.5.2 (Build 22G91)

### LinearMouse

v0.9.5

### Is your feature request related to a problem?

my external mouse wakes up my macbook a second after I put it to sleep. Slightest random movement like just putting my hand on the desk wakes it up...

### Describe the solution you'd like

I'd like an option to disable external mouse from waking up my macbook.

### Describe alternatives you've considered

There was a way to disable bluetooth devices from waking up your mac... but it seems meesing in the new version of macos. And... i only want to disable my mouse from waking up my mac. Not the keyboard.

**Comment by lujjjh** [comment]
It sounds like a very useful feature, but I'm not sure if it can be implemented in macOS since sleep/wake is not something that can be controlled by programs. One solution I can think of is to automatically "disable" the external mouse device before entering sleep and then "reactivate" it after waking up, but I'm not sure if this can be done.
