### ISSUE TITLE
Slider for Scrolling Speed modifier is laggy

### ISSUE THREAD

**Issue by douira** [linearmouse/linearmouse#63]
This slider is very helpful but it's laggy to use. I'm guessing this is because it's displaying a very large amount of tick marks. Maybe just make it non-discrete and have any value be acceptable? Additionally, this feature would be even more helpful to me if it was possible to set the value to less than 0.1. I use this for fine control over side scrolling which I sometimes want to do in a precise way and having this be even smaller, like 0.03 for example would be very nice. Thanks for the great app!
<img width="612" alt="Screenshot 2022-01-30 at 18 52 23" src="https://user-images.githubusercontent.com/17120022/151711247-76785b33-0d32-427f-97c5-60cfd573a223.png">

**Comment by lujjjh** [comment]
Thank you for your feedback!

> This slider is very helpful but it's laggy to use. I'm guessing this is because it's displaying a very large amount of tick marks.

Yes, you're right. I've removed these tick marks.

Also, the minimal scrolling unit in the current version is one line. So even with speed factor 0.1x, it may still scroll too fast.

I'm trying to get it fixed in [this pre-release](https://github.com/linearmouse/linearmouse/actions/runs/1785376751). Would you like to test if it works as expected?

**Comment by douira** [comment]
I'm using the pre-release you've provided and it works great! The slider moves smoothly and goes down to 0.05 which is sufficient for my use case. Thanks! You can close this issue as you like.
