### ISSUE TITLE
Cannot adjust LinearMouse settings

### ISSUE THREAD

**Issue by taninke** [linearmouse/linearmouse#631]
### OS

14.1 Beta (23B5067a)

### LinearMouse

0.9.5

### Describe the bug

Unable to adjust pointer acceleration or pointer speed options in linearmouse

Issuer persisted on MacOS 14, and I updated to 14.1 developer beta to see if any resolution could be found

### To reproduce

- Open linearmouse
- Go to pointer options
- Try to drag or type values for pointer acceleration or pointer speed
- Resets to previous value
- Resetting to system defaults does not take an action

### Expected behavior

The ability to manually type or adjust the pointer acceleration and pointer speed settings

### Anything else?

[LinearMouse.log](https://github.com/linearmouse/linearmouse/files/12887520/LinearMouse.log)

**Comment by lujjjh** [comment]
There could be other schemes that override the pointer settings. Would you mind sharing and uploading your configuration file here? You should be able to locate it by going to Config and selecting "Reveal in Finder."

**Comment by taninke** [comment]
> There could be other schemes that override the pointer settings. Would you mind sharing and uploading your configuration file here? You should be able to locate it by going to Config and selecting "Reveal in Finder."

[linearmouse.json](https://github.com/linearmouse/linearmouse/files/12899255/linearmouse.json)

Hopefully this helps!

**Comment by lujjjh** [comment]
It should be fixed by removing the duplicated scheme from `linearmouse.json`:

```diff
@@ -82,21 +82,6 @@
         }
       }
     },
-    {
-      "if" : {
-        "device" : {
-          "category" : "mouse",
-          "vendorID" : "0x46d",
-          "productName" : "MX Master 3",
-          "productID" : "0xb023"
-        }
-      },
-      "pointer" : {
-        "disableAcceleration" : false,
-        "acceleration" : 0.688,
-        "speed" : 0.08
-      }
-    },
     {
       "if" : {
         "device" : {
```

You could overwrite your `linearmouse.json` with [the modified one](https://github.com/linearmouse/linearmouse/files/12902379/linearmouse.json) and reload the config.

LinearMouse generated a duplicated scheme because it matches a device based on its product id, vendor id, serial number, and other factors.

However, it appears that once in the past, your MX Master 3 did not report its serial number (possibly due to having multiple MX Master 3 devices? or bugs in macOS beta?). And you might have reconfigured the pointer settings at that time.

As a result, LinearMouse created another scheme for the MX Master 3 without considering its serial number.

**Comment by taninke** [comment]
Thanks @lujjjh that seemed to have resolved it!

Is there a way to simply remove per-app configuration as well? It seems there isn't a way to do so simply within the application, do we just have to remove it from the config file?
