### ISSUE TITLE
Tracking speed doesn't match Pointer speed with acceleration set to 0

### ISSUE THREAD

**Issue by ericvw** [linearmouse/linearmouse#642]
### OS

macOS 14.1

### LinearMouse

v0.9.5

### Describe the bug

I was under the impression that with pointer acceleration set to 0 and pointer speed set to 1, it should match the same behavior when pointer acceleration is disabled with tracking speed set to 1. When I move the mouse across the screen in both scenarios, it tracks at a different distance on the screen for the same physical mouse movement.

For background, I want to determine what Pointer settings I should use with Linear Mouse when using Logitech GHub software to ensure that the DPI set for my Logitech mouse is the actual DPI being used.

I also noticed that when toggling "Disable pointer acceleration," the value of "Pointer acceleration" is taken from "Tracking speed," and vice-versa. 

### To reproduce

1. Go to Pointer settings.
2. Untoggle "Disable pointer acceleration."
3. Set Pointer acceleration to 0.
4. Set Ponter speed to 1.
5. Move the mouse around across the screen.

1. Now, toggle "Disable pointer acceleration."
2. Set Tracking speed to 1
3. Move the mouse around across the screen.

### Expected behavior

The tracking speed and distance to be the same.

**Comment by lujjjh** [comment]
Pointer speed is essentially the inverse of pointer resolution, which can be simply understood as a scaling of the movement speed of the cursor. A value of 1 isn't a special value for pointer speed, so the different movement speeds you're experiencing in the two scenarios you mentioned are to be expected.

There have been discussions before about how to configure the pointer speed to be exactly the same as on Windows. However, due to the closed-source nature of both macOS and Windows, answering this question isn't straightforward.

If you want to obtain an accurate DPI, my suggestion is to use a [DPI analyzer](https://www.mouse-sensitivity.com/dpianalyzer/) to measure the actual DPI, and then adjust the pointer speed according to the ratio between the measured DPI and your target DPI.

**Comment by ericvw** [comment]
Thanks for explaining the definition of the pointer speed.

How is tracking speed (when pointer acceleration toggle is disabled) different from pointer speed?

I guess I am trying to get at if I set a DPI by some third-party software, should I have the pointer acceleration toggle enabled or disabled to adjust either pointer speed or tracking speed, respectively, to achieve the desired DPI? What do you recommend?

**Comment by lujjjh** [comment]
Since you are using macOS Sonoma, I would suggest disabling pointer acceleration and adjusting the tracking speed instead of merely setting it to zero. This approach, a new feature in Sonoma, effectively and completely turns off pointer acceleration.

**Comment by lujjjh** [comment]
I'm closing this issue. Please feel free to reopen it if you have any further questions. :)

**Comment by ericvw** [comment]
As a note for others, turning off pointer acceleration and setting the tracking speed to 1 results in the DPI matching what is specified by third-party mouse software (e.g., Logitech G Hub).
