### ISSUE TITLE
sensitivity 5-1800

### ISSUE THREAD

**Issue by sealvessel** [linearmouse/linearmouse#83]
Which sensitivity is the default. Please add a stepped default line on where it is the default system sensitivity at which it is equivalent to defaults write -g com.apple.mouse.scaling -1, otherwise I don't have a use for this application.

**Comment by lujjjh** [comment]
The default sensitivity is up to the device. For most devices, the default sensitivity is 1600. You may click ‘Revert to system defaults’ to revert sensitivity to that value. For other devices, the default sensitivity varies, for example, the [Magic Mouse](https://github.com/linearmouse/linearmouse/issues/33#issuecomment-995919134).

`defaults write -g com.apple.mouse.scaling -1` is actually to disable cursor *acceleration*, rather than reverting to the default *sensitivity*. But cursor sensitivity will also be disabled as a side effect. You may turn on ‘Disable cursor acceleration & sensitivity’ which is basically equivalent to it.
