### ISSUE TITLE
Disable annoying auto update?

### ISSUE THREAD

**Issue by vis2k** [linearmouse/linearmouse#88]
First off, thanks a lot for this great tool.
It works beautifully, and there in lies the issue.

Please could you stop nagging me with update pop ups every few days?
The tool is fine. It disable mouse acceleration. I don't want it to update.

What I want is to work on my stuff without constant interruptions.
The nag screen is way out of proportions for a mouse acceleration tool, and there's no 'stop asking' option.

Could you please make this optional, and/or share the update url for a block in hosts file?

**Comment by lujjjh** [comment]
Oops! I was focused on resolving issues and didn't realize it. I'll add a switch to turn on / off auto update.

After basic features are stable, I'll provide multiple update channels (stable / beta). Since then, the release frequency should be rather constant.

Note: If you disable auto update, make sure to update LinearMouse manually before the code signing certificate expires. Or you'll get the message in #43.

**Comment by vis2k** [comment]
oh wow. thanks mate!
